### PR TITLE
Fix syntax error in roomCard

### PR DESCRIPTION
**Pull request by scij**
parameter defaults must spell defaultValue

### CODE REVIEW

**Comment by florian-h05** [comment]
Thanks for your PR, nice to see that someone is using my widgets!

However, I’ve checked the MainUI code and the MainUI expects `default` for default values of properties:

https://github.com/openhab/openhab-webui/blob/095bb2f9cba78d17d138dd32c975f271a2e13845/bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js#L78

Can you please explain why you think it is defaultValue or provide any reference?

**Comment by scij** [comment]
Hi Florian,

When I try to add the widget to my Openhab 3.4.3 installation via Setting / User Interfaces / Widgets the installation fails (silently) and I get this message in my log:

```
2023-05-04 16:35:14.178 [ERROR] [munity.CommunityUIWidgetAddonHandler] - Unable to parse YAML: Unrecognized field "default" (class org.openhab.core.config.core.dto.ConfigDescriptionParameterDTO), not marked as ignorable (22 known properties: "readOnly", "max", "limitToOptions", "groupName", "name", "stepsize", "context", "defaultValue", "min", "label", "filterCriteria", "verify", "type", "description", "options", "required", "advanced", "unit", "multipleLimit", "pattern", "multiple", "unitLabel"])
 at [Source: (StringReader); line: 20, column: 21] (through reference chain: org.openhab.core.ui.components.RootUIComponent["props"]->org.openhab.core.config.core.dto.ConfigDescriptionDTO["parameters"]->java.util.ArrayList[2]->org.openhab.core.config.core.dto.ConfigDescriptionParameterDTO["default"])
2023-05-04 16:35:14.191 [ERROR] [munity.CommunityUIWidgetAddonHandler] - Widget from marketplace is invalid: Unable to parse YAML
```

Is this a OH versioning issue?

Thank you and best regards
 Jürgen

**Comment by florian-h05** [comment]
Hello Jürgen,

> Is this a OH versioning issue?

No, nothing with versioning. Instead, there seems to be an issue with the DTO (Data Transfer Object) in openHAB Core, I’ll have a look at that and talk to the core maintainers.

**Comment by florian-h05** [comment]
I've just tried to reproduce this, but I can install and use the widget from the marketplace on the latest 4.0 SNAPSHOT build (I am on `#3477` currently). So it seems like the underlying issue has been fixed, and this can be closed.

WDYT?

**Pull request closed without merging**
